# Generated by Django 3.1.4 on 2020-12-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='long_url',
            field=models.CharField(max_length=4096),
        ),
    ]
