# Generated by Django 3.1.4 on 2020-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201223_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlinfo',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
